// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/analytics/query.proto

package analytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Query service

type QueryService interface {
	// 个体
	Agent(ctx context.Context, in *QueryAgentRequest, opts ...client.CallOption) (*QueryAgentResponse, error)
}

type queryService struct {
	c    client.Client
	name string
}

func NewQueryService(name string, c client.Client) QueryService {
	return &queryService{
		c:    c,
		name: name,
	}
}

func (c *queryService) Agent(ctx context.Context, in *QueryAgentRequest, opts ...client.CallOption) (*QueryAgentResponse, error) {
	req := c.c.NewRequest(c.name, "Query.Agent", in)
	out := new(QueryAgentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Query service

type QueryHandler interface {
	// 个体
	Agent(context.Context, *QueryAgentRequest, *QueryAgentResponse) error
}

func RegisterQueryHandler(s server.Server, hdlr QueryHandler, opts ...server.HandlerOption) error {
	type query interface {
		Agent(ctx context.Context, in *QueryAgentRequest, out *QueryAgentResponse) error
	}
	type Query struct {
		query
	}
	h := &queryHandler{hdlr}
	return s.Handle(s.NewHandler(&Query{h}, opts...))
}

type queryHandler struct {
	QueryHandler
}

func (h *queryHandler) Agent(ctx context.Context, in *QueryAgentRequest, out *QueryAgentResponse) error {
	return h.QueryHandler.Agent(ctx, in, out)
}
