// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/analytics/query.proto

package analytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 查询个体的请求
type QueryAgentRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentRequest) Reset()         { *m = QueryAgentRequest{} }
func (m *QueryAgentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAgentRequest) ProtoMessage()    {}
func (*QueryAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf75dbd117f0a908, []int{0}
}

func (m *QueryAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentRequest.Unmarshal(m, b)
}
func (m *QueryAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentRequest.Marshal(b, m, deterministic)
}
func (m *QueryAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentRequest.Merge(m, src)
}
func (m *QueryAgentRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAgentRequest.Size(m)
}
func (m *QueryAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentRequest proto.InternalMessageInfo

func (m *QueryAgentRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryAgentRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// 查询个体的回复
type QueryAgentResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Total                int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Agent                []*Agent `protobuf:"bytes,3,rep,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAgentResponse) Reset()         { *m = QueryAgentResponse{} }
func (m *QueryAgentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAgentResponse) ProtoMessage()    {}
func (*QueryAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf75dbd117f0a908, []int{1}
}

func (m *QueryAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAgentResponse.Unmarshal(m, b)
}
func (m *QueryAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAgentResponse.Marshal(b, m, deterministic)
}
func (m *QueryAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAgentResponse.Merge(m, src)
}
func (m *QueryAgentResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAgentResponse.Size(m)
}
func (m *QueryAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAgentResponse proto.InternalMessageInfo

func (m *QueryAgentResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *QueryAgentResponse) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *QueryAgentResponse) GetAgent() []*Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

// 查询事件的请求
type QueryEventRequest struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	AppID                string   `protobuf:"bytes,3,opt,name=appID,proto3" json:"appID,omitempty"`
	DeviceID             string   `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	UserID               string   `protobuf:"bytes,5,opt,name=userID,proto3" json:"userID,omitempty"`
	EventID              string   `protobuf:"bytes,6,opt,name=eventID,proto3" json:"eventID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryEventRequest) Reset()         { *m = QueryEventRequest{} }
func (m *QueryEventRequest) String() string { return proto.CompactTextString(m) }
func (*QueryEventRequest) ProtoMessage()    {}
func (*QueryEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf75dbd117f0a908, []int{2}
}

func (m *QueryEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryEventRequest.Unmarshal(m, b)
}
func (m *QueryEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryEventRequest.Marshal(b, m, deterministic)
}
func (m *QueryEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryEventRequest.Merge(m, src)
}
func (m *QueryEventRequest) XXX_Size() int {
	return xxx_messageInfo_QueryEventRequest.Size(m)
}
func (m *QueryEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryEventRequest proto.InternalMessageInfo

func (m *QueryEventRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *QueryEventRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryEventRequest) GetAppID() string {
	if m != nil {
		return m.AppID
	}
	return ""
}

func (m *QueryEventRequest) GetDeviceID() string {
	if m != nil {
		return m.DeviceID
	}
	return ""
}

func (m *QueryEventRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *QueryEventRequest) GetEventID() string {
	if m != nil {
		return m.EventID
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryAgentRequest)(nil), "analytics.QueryAgentRequest")
	proto.RegisterType((*QueryAgentResponse)(nil), "analytics.QueryAgentResponse")
	proto.RegisterType((*QueryEventRequest)(nil), "analytics.QueryEventRequest")
}

func init() {
	proto.RegisterFile("proto/analytics/query.proto", fileDescriptor_cf75dbd117f0a908)
}

var fileDescriptor_cf75dbd117f0a908 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xd1, 0x4e, 0x83, 0x30,
	0x14, 0x86, 0x45, 0x2c, 0xba, 0xb3, 0x1b, 0xd7, 0x18, 0xd3, 0xe0, 0x4c, 0x08, 0x17, 0x06, 0x6f,
	0x58, 0x82, 0x4f, 0x80, 0x41, 0x13, 0x2e, 0xc5, 0x27, 0xa8, 0xac, 0xd3, 0x45, 0x42, 0x19, 0x2d,
	0x4b, 0x76, 0xe1, 0x4b, 0xf8, 0x0e, 0xbe, 0xa7, 0xe9, 0x29, 0x43, 0xe2, 0xe2, 0x8d, 0x97, 0xff,
	0xff, 0x9f, 0x7e, 0x9c, 0xbf, 0x14, 0xae, 0x9a, 0x56, 0x6a, 0xb9, 0xe0, 0x35, 0xaf, 0x76, 0x7a,
	0x5d, 0xaa, 0xc5, 0xa6, 0x13, 0xed, 0x2e, 0x46, 0x97, 0x4e, 0x06, 0xdb, 0x9f, 0xff, 0x9e, 0x53,
	0x6f, 0xbc, 0x15, 0x4b, 0x3b, 0x18, 0xa6, 0x30, 0x7b, 0x32, 0xe7, 0xd2, 0x57, 0x51, 0xeb, 0x42,
	0x6c, 0x3a, 0xa1, 0x34, 0xbd, 0x04, 0x4f, 0xae, 0x56, 0x4a, 0x68, 0xe6, 0x04, 0x4e, 0xe4, 0x16,
	0xbd, 0xa2, 0x17, 0x40, 0x4a, 0xd9, 0xd5, 0x9a, 0x1d, 0xa3, 0x6d, 0x45, 0xf8, 0x01, 0x74, 0x8c,
	0x50, 0x8d, 0xac, 0x95, 0xa0, 0xb7, 0xe0, 0x29, 0xcd, 0x75, 0xa7, 0x90, 0x31, 0x4d, 0x66, 0xf1,
	0xb0, 0x41, 0xfc, 0x8c, 0x41, 0xd1, 0x0f, 0x18, 0xac, 0x96, 0x9a, 0x57, 0x7b, 0x2c, 0x0a, 0x7a,
	0x03, 0x84, 0x1b, 0x22, 0x73, 0x03, 0x37, 0x9a, 0x26, 0xe7, 0xa3, 0xf3, 0xf6, 0x4b, 0x36, 0x0e,
	0xbf, 0x9c, 0xbe, 0xc2, 0xc3, 0xf6, 0xbf, 0x15, 0x8c, 0xcb, 0x9b, 0x26, 0xcf, 0x98, 0x1b, 0x38,
	0xd1, 0xa4, 0xb0, 0x82, 0xfa, 0x70, 0xb6, 0x14, 0xdb, 0x75, 0x29, 0xf2, 0x8c, 0x9d, 0x60, 0x30,
	0x68, 0xc3, 0xef, 0x94, 0x68, 0xf3, 0x8c, 0x11, 0x4c, 0x7a, 0x45, 0x19, 0x9c, 0x0a, 0xb3, 0x47,
	0x9e, 0x31, 0x0f, 0x83, 0xbd, 0x4c, 0x3e, 0x1d, 0x20, 0xb8, 0x27, 0x7d, 0x04, 0x82, 0x0d, 0xe8,
	0x7c, 0xd4, 0xe9, 0xe0, 0x2f, 0xf8, 0xd7, 0x7f, 0xa4, 0xf6, 0x82, 0xc3, 0x23, 0x9a, 0x02, 0xc1,
	0xce, 0x87, 0x9c, 0xf1, 0x55, 0xf8, 0x6c, 0x94, 0xde, 0x57, 0xbc, 0x7e, 0xff, 0x41, 0xbc, 0x78,
	0xf8, 0x0a, 0xee, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x90, 0x2c, 0xbc, 0x4d, 0x02, 0x00,
	0x00,
}
