// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/analytics/query.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 查询个体的请求
type QueryAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"` // 偏移量
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`   // 数量
}

func (x *QueryAgentRequest) Reset() {
	*x = QueryAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_query_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentRequest) ProtoMessage() {}

func (x *QueryAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_query_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentRequest.ProtoReflect.Descriptor instead.
func (*QueryAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryAgentRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryAgentRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 查询个体的回复
type QueryAgentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 状态
	Total  int64    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`  // 总数
	Agent  []*Agent `protobuf:"bytes,3,rep,name=agent,proto3" json:"agent,omitempty"`   // 个体列表
}

func (x *QueryAgentResponse) Reset() {
	*x = QueryAgentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_query_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAgentResponse) ProtoMessage() {}

func (x *QueryAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_query_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAgentResponse.ProtoReflect.Descriptor instead.
func (*QueryAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAgentResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryAgentResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *QueryAgentResponse) GetAgent() []*Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// 查询事件的请求
type QueryEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset     int64  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`         // 偏移量
	Count      int64  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`           // 数量
	StartTime  int64  `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`   // 开始时间
	EndTime    int64  `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`       // 结束时间
	AppID      string `protobuf:"bytes,5,opt,name=appID,proto3" json:"appID,omitempty"`            // 应用ID
	DeviceID   string `protobuf:"bytes,6,opt,name=deviceID,proto3" json:"deviceID,omitempty"`      // 设备ID
	UserID     string `protobuf:"bytes,7,opt,name=userID,proto3" json:"userID,omitempty"`          // 用户ID
	EventID    string `protobuf:"bytes,8,opt,name=eventID,proto3" json:"eventID,omitempty"`        // 事件ID
	EventKey   string `protobuf:"bytes,9,opt,name=eventKey,proto3" json:"eventKey,omitempty"`      // 事件键
	EventValue string `protobuf:"bytes,10,opt,name=eventValue,proto3" json:"eventValue,omitempty"` // 事件值
	Template   string `protobuf:"bytes,11,opt,name=template,proto3" json:"template,omitempty"`     // 报表模板
}

func (x *QueryEventRequest) Reset() {
	*x = QueryEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_query_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventRequest) ProtoMessage() {}

func (x *QueryEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_query_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventRequest.ProtoReflect.Descriptor instead.
func (*QueryEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryEventRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *QueryEventRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueryEventRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryEventRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryEventRequest) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *QueryEventRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *QueryEventRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *QueryEventRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *QueryEventRequest) GetEventKey() string {
	if x != nil {
		return x.EventKey
	}
	return ""
}

func (x *QueryEventRequest) GetEventValue() string {
	if x != nil {
		return x.EventValue
	}
	return ""
}

func (x *QueryEventRequest) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// 查询事件的回复
type QueryEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // 状态
	Content string  `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 报表内容
}

func (x *QueryEventResponse) Reset() {
	*x = QueryEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_query_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEventResponse) ProtoMessage() {}

func (x *QueryEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_query_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEventResponse.ProtoReflect.Descriptor instead.
func (*QueryEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryEventResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *QueryEventResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_analytics_query_proto protoreflect.FileDescriptor

var file_proto_analytics_query_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x11, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x69,
	0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x05, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0xb5, 0x02, 0x0a, 0x11, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74,
	0x65, 0x22, 0x4f, 0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x32, 0x6f, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x32, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x3b, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_analytics_query_proto_rawDescOnce sync.Once
	file_proto_analytics_query_proto_rawDescData = file_proto_analytics_query_proto_rawDesc
)

func file_proto_analytics_query_proto_rawDescGZIP() []byte {
	file_proto_analytics_query_proto_rawDescOnce.Do(func() {
		file_proto_analytics_query_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_analytics_query_proto_rawDescData)
	})
	return file_proto_analytics_query_proto_rawDescData
}

var file_proto_analytics_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_analytics_query_proto_goTypes = []interface{}{
	(*QueryAgentRequest)(nil),  // 0: QueryAgentRequest
	(*QueryAgentResponse)(nil), // 1: QueryAgentResponse
	(*QueryEventRequest)(nil),  // 2: QueryEventRequest
	(*QueryEventResponse)(nil), // 3: QueryEventResponse
	(*Status)(nil),             // 4: Status
	(*Agent)(nil),              // 5: Agent
}
var file_proto_analytics_query_proto_depIdxs = []int32{
	4, // 0: QueryAgentResponse.status:type_name -> Status
	5, // 1: QueryAgentResponse.agent:type_name -> Agent
	4, // 2: QueryEventResponse.status:type_name -> Status
	0, // 3: Query.Agent:input_type -> QueryAgentRequest
	2, // 4: Query.Event:input_type -> QueryEventRequest
	1, // 5: Query.Agent:output_type -> QueryAgentResponse
	3, // 6: Query.Event:output_type -> QueryEventResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_analytics_query_proto_init() }
func file_proto_analytics_query_proto_init() {
	if File_proto_analytics_query_proto != nil {
		return
	}
	file_proto_analytics_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_analytics_query_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_query_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAgentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_query_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_analytics_query_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_analytics_query_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_query_proto_goTypes,
		DependencyIndexes: file_proto_analytics_query_proto_depIdxs,
		MessageInfos:      file_proto_analytics_query_proto_msgTypes,
	}.Build()
	File_proto_analytics_query_proto = out.File
	file_proto_analytics_query_proto_rawDesc = nil
	file_proto_analytics_query_proto_goTypes = nil
	file_proto_analytics_query_proto_depIdxs = nil
}
