// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/analytics/record.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 记录活动的请求
type RecordActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppID     string       `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`         // 应用ID
	DeviceID  string       `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`   // 设备ID
	UserID    string       `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户ID
	Parameter []*Parameter `protobuf:"bytes,5,rep,name=parameter,proto3" json:"parameter,omitempty"` // 参数
}

func (x *RecordActivityRequest) Reset() {
	*x = RecordActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityRequest) ProtoMessage() {}

func (x *RecordActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_record_proto_rawDescGZIP(), []int{0}
}

func (x *RecordActivityRequest) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *RecordActivityRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *RecordActivityRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RecordActivityRequest) GetParameter() []*Parameter {
	if x != nil {
		return x.Parameter
	}
	return nil
}

var File_proto_analytics_record_proto protoreflect.FileDescriptor

var file_proto_analytics_record_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2f,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8b, 0x01, 0x0a,
	0x15, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x28, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52,
	0x09, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x32, 0x60, 0x0a, 0x06, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x57, 0x61, 0x6b, 0x65, 0x12, 0x06, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x12, 0x16, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x3b,
	0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_analytics_record_proto_rawDescOnce sync.Once
	file_proto_analytics_record_proto_rawDescData = file_proto_analytics_record_proto_rawDesc
)

func file_proto_analytics_record_proto_rawDescGZIP() []byte {
	file_proto_analytics_record_proto_rawDescOnce.Do(func() {
		file_proto_analytics_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_analytics_record_proto_rawDescData)
	})
	return file_proto_analytics_record_proto_rawDescData
}

var file_proto_analytics_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_analytics_record_proto_goTypes = []interface{}{
	(*RecordActivityRequest)(nil), // 0: RecordActivityRequest
	(*Parameter)(nil),             // 1: Parameter
	(*Agent)(nil),                 // 2: Agent
	(*BlankResponse)(nil),         // 3: BlankResponse
}
var file_proto_analytics_record_proto_depIdxs = []int32{
	1, // 0: RecordActivityRequest.parameter:type_name -> Parameter
	2, // 1: Record.Wake:input_type -> Agent
	0, // 2: Record.Activity:input_type -> RecordActivityRequest
	3, // 3: Record.Wake:output_type -> BlankResponse
	3, // 4: Record.Activity:output_type -> BlankResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analytics_record_proto_init() }
func file_proto_analytics_record_proto_init() {
	if File_proto_analytics_record_proto != nil {
		return
	}
	file_proto_analytics_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_analytics_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecordActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_analytics_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_record_proto_goTypes,
		DependencyIndexes: file_proto_analytics_record_proto_depIdxs,
		MessageInfos:      file_proto_analytics_record_proto_msgTypes,
	}.Build()
	File_proto_analytics_record_proto = out.File
	file_proto_analytics_record_proto_rawDesc = nil
	file_proto_analytics_record_proto_goTypes = nil
	file_proto_analytics_record_proto_depIdxs = nil
}
