// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/analytics/shared.proto

package analytics

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 状态
type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_90d1d37448e1e928, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// 空白回复
type BlankResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlankResponse) Reset()         { *m = BlankResponse{} }
func (m *BlankResponse) String() string { return proto.CompactTextString(m) }
func (*BlankResponse) ProtoMessage()    {}
func (*BlankResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90d1d37448e1e928, []int{1}
}

func (m *BlankResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlankResponse.Unmarshal(m, b)
}
func (m *BlankResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlankResponse.Marshal(b, m, deterministic)
}
func (m *BlankResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlankResponse.Merge(m, src)
}
func (m *BlankResponse) XXX_Size() int {
	return xxx_messageInfo_BlankResponse.Size(m)
}
func (m *BlankResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlankResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlankResponse proto.InternalMessageInfo

func (m *BlankResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type Agent struct {
	SerialNumber         string   `protobuf:"bytes,1,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`
	SoftwareFamily       string   `protobuf:"bytes,2,opt,name=softwareFamily,proto3" json:"softwareFamily,omitempty"`
	SoftwareVersion      string   `protobuf:"bytes,3,opt,name=softwareVersion,proto3" json:"softwareVersion,omitempty"`
	SystemFamily         string   `protobuf:"bytes,4,opt,name=systemFamily,proto3" json:"systemFamily,omitempty"`
	SystemVersion        string   `protobuf:"bytes,5,opt,name=systemVersion,proto3" json:"systemVersion,omitempty"`
	DeviceModel          string   `protobuf:"bytes,6,opt,name=deviceModel,proto3" json:"deviceModel,omitempty"`
	DeviceType           string   `protobuf:"bytes,7,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_90d1d37448e1e928, []int{2}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetSerialNumber() string {
	if m != nil {
		return m.SerialNumber
	}
	return ""
}

func (m *Agent) GetSoftwareFamily() string {
	if m != nil {
		return m.SoftwareFamily
	}
	return ""
}

func (m *Agent) GetSoftwareVersion() string {
	if m != nil {
		return m.SoftwareVersion
	}
	return ""
}

func (m *Agent) GetSystemFamily() string {
	if m != nil {
		return m.SystemFamily
	}
	return ""
}

func (m *Agent) GetSystemVersion() string {
	if m != nil {
		return m.SystemVersion
	}
	return ""
}

func (m *Agent) GetDeviceModel() string {
	if m != nil {
		return m.DeviceModel
	}
	return ""
}

func (m *Agent) GetDeviceType() string {
	if m != nil {
		return m.DeviceType
	}
	return ""
}

func init() {
	proto.RegisterType((*Status)(nil), "analytics.Status")
	proto.RegisterType((*BlankResponse)(nil), "analytics.BlankResponse")
	proto.RegisterType((*Agent)(nil), "analytics.Agent")
}

func init() {
	proto.RegisterFile("proto/analytics/shared.proto", fileDescriptor_90d1d37448e1e928)
}

var fileDescriptor_90d1d37448e1e928 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x49, 0xbf, 0x26, 0x25, 0xd3, 0xaf, 0x8a, 0x73, 0xda, 0x83, 0x48, 0x08, 0x22, 0xf1,
	0x92, 0x82, 0x82, 0x07, 0x6f, 0x7a, 0xf0, 0xa6, 0x87, 0x28, 0xde, 0xb7, 0xc9, 0x58, 0x83, 0x49,
	0x36, 0xec, 0x6c, 0x95, 0xfc, 0x04, 0xff, 0xb5, 0x30, 0x49, 0x4a, 0xda, 0xdb, 0xbe, 0x0f, 0xcf,
	0xbe, 0xef, 0xc2, 0xc2, 0x79, 0x6b, 0x8d, 0x33, 0x6b, 0xdd, 0xe8, 0xaa, 0x73, 0x65, 0xce, 0x6b,
	0xfe, 0xd4, 0x96, 0x8a, 0x54, 0x30, 0x86, 0x7b, 0x1e, 0xdf, 0x41, 0xf0, 0xea, 0xb4, 0xdb, 0x31,
	0x22, 0xcc, 0x73, 0x53, 0x90, 0xf2, 0x22, 0x2f, 0xf1, 0x33, 0x39, 0xa3, 0x82, 0x45, 0x4d, 0xcc,
	0x7a, 0x4b, 0x6a, 0x16, 0x79, 0x49, 0x98, 0x8d, 0x31, 0xbe, 0x87, 0xd5, 0x63, 0xa5, 0x9b, 0xaf,
	0x8c, 0xb8, 0x35, 0x0d, 0x13, 0x5e, 0x43, 0xc0, 0x52, 0x24, 0x05, 0xcb, 0x9b, 0xb3, 0x74, 0x3f,
	0x92, 0xf6, 0x0b, 0xd9, 0x20, 0xc4, 0xbf, 0x33, 0xf0, 0x1f, 0xb6, 0xd4, 0x38, 0x8c, 0xe1, 0x3f,
	0x93, 0x2d, 0x75, 0xf5, 0xb2, 0xab, 0x37, 0x64, 0xe5, 0x6a, 0x98, 0x1d, 0x30, 0xbc, 0x82, 0x13,
	0x36, 0x1f, 0xee, 0x47, 0x5b, 0x7a, 0xd2, 0x75, 0x59, 0x75, 0xc3, 0x53, 0x8e, 0x28, 0x26, 0x70,
	0x3a, 0x92, 0x77, 0xb2, 0x5c, 0x9a, 0x46, 0xfd, 0x13, 0xf1, 0x18, 0xcb, 0x6a, 0xc7, 0x8e, 0xea,
	0xa1, 0x6f, 0x3e, 0xac, 0x4e, 0x18, 0x5e, 0xc2, 0xaa, 0xcf, 0x63, 0x97, 0x2f, 0xd2, 0x21, 0xc4,
	0x08, 0x96, 0x05, 0x7d, 0x97, 0x39, 0x3d, 0x9b, 0x82, 0x2a, 0x15, 0x88, 0x33, 0x45, 0x78, 0x01,
	0xd0, 0xc7, 0xb7, 0xae, 0x25, 0xb5, 0x10, 0x61, 0x42, 0x36, 0x81, 0xfc, 0xc8, 0xed, 0x5f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x79, 0x92, 0xdd, 0xf5, 0xb1, 0x01, 0x00, 0x00,
}
