// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/analytics/tracker.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 跟踪记录的请求
type TrackerRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppID     string `protobuf:"bytes,1,opt,name=appID,proto3" json:"appID,omitempty"`         // 应用ID
	DeviceID  string `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`   // 设备ID
	UserID    string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`       // 用户ID
	EventID   string `protobuf:"bytes,4,opt,name=eventID,proto3" json:"eventID,omitempty"`     // 事件ID
	Parameter string `protobuf:"bytes,5,opt,name=parameter,proto3" json:"parameter,omitempty"` // 参数
}

func (x *TrackerRecordRequest) Reset() {
	*x = TrackerRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_analytics_tracker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackerRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackerRecordRequest) ProtoMessage() {}

func (x *TrackerRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_tracker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackerRecordRequest.ProtoReflect.Descriptor instead.
func (*TrackerRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_tracker_proto_rawDescGZIP(), []int{0}
}

func (x *TrackerRecordRequest) GetAppID() string {
	if x != nil {
		return x.AppID
	}
	return ""
}

func (x *TrackerRecordRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

func (x *TrackerRecordRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *TrackerRecordRequest) GetEventID() string {
	if x != nil {
		return x.EventID
	}
	return ""
}

func (x *TrackerRecordRequest) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

var File_proto_analytics_tracker_proto protoreflect.FileDescriptor

var file_proto_analytics_tracker_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63,
	0x73, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73,
	0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x01,
	0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x32, 0x5e, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x04, 0x57, 0x61, 0x6b, 0x65, 0x12, 0x06, 0x2e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12,
	0x15, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x42, 0x6c, 0x61, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x3b, 0x61, 0x6e, 0x61, 0x6c,
	0x79, 0x74, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_analytics_tracker_proto_rawDescOnce sync.Once
	file_proto_analytics_tracker_proto_rawDescData = file_proto_analytics_tracker_proto_rawDesc
)

func file_proto_analytics_tracker_proto_rawDescGZIP() []byte {
	file_proto_analytics_tracker_proto_rawDescOnce.Do(func() {
		file_proto_analytics_tracker_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_analytics_tracker_proto_rawDescData)
	})
	return file_proto_analytics_tracker_proto_rawDescData
}

var file_proto_analytics_tracker_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_analytics_tracker_proto_goTypes = []interface{}{
	(*TrackerRecordRequest)(nil), // 0: TrackerRecordRequest
	(*Agent)(nil),                // 1: Agent
	(*BlankResponse)(nil),        // 2: BlankResponse
}
var file_proto_analytics_tracker_proto_depIdxs = []int32{
	1, // 0: Tracker.Wake:input_type -> Agent
	0, // 1: Tracker.Record:input_type -> TrackerRecordRequest
	2, // 2: Tracker.Wake:output_type -> BlankResponse
	2, // 3: Tracker.Record:output_type -> BlankResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_tracker_proto_init() }
func file_proto_analytics_tracker_proto_init() {
	if File_proto_analytics_tracker_proto != nil {
		return
	}
	file_proto_analytics_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_analytics_tracker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackerRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_analytics_tracker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_tracker_proto_goTypes,
		DependencyIndexes: file_proto_analytics_tracker_proto_depIdxs,
		MessageInfos:      file_proto_analytics_tracker_proto_msgTypes,
	}.Build()
	File_proto_analytics_tracker_proto = out.File
	file_proto_analytics_tracker_proto_rawDesc = nil
	file_proto_analytics_tracker_proto_goTypes = nil
	file_proto_analytics_tracker_proto_depIdxs = nil
}
